application:
  swagger:
    title: @name@
    description: @description@
    version: @version@
#  mvc:
#    pathmatch.matching-strategy: ant_path_matcher

server:
    port: 8082
kafka:
  bootstrapAddress: localhost:9092
  schemaRegistry: http://localhost:8081
  topics:
    send.avro: sendProductAvro

logging:
  level:
    root: INFO